import ExcelJS from "exceljs";

export const excelReportService = {
  async generateLeaveSummaryWorkbook(reportData) {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = "LeaveEase Management System";
    workbook.created = new Date();

    const { metadata, summary, details, employee_summary, team_summary, exceptions } = reportData;

    // Palette styles
    const headerFill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF1E293B" }, // Slate 800
    };
    const headerFont = {
      name: "Calibri",
      size: 11,
      bold: true,
      color: { argb: "FFFFFFFF" },
    };
    const subHeaderFill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF334155" }, // Slate 700
    };
    const accentFill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFF1F5F9" }, // Slate 100
    };
    const thinBorder = {
      top: { style: "thin", color: { argb: "FFE2E8F0" } },
      left: { style: "thin", color: { argb: "FFE2E8F0" } },
      bottom: { style: "thin", color: { argb: "FFE2E8F0" } },
      right: { style: "thin", color: { argb: "FFE2E8F0" } },
    };

    // =========================================================================
    // SHEET 1: Report Summary
    // =========================================================================
    const s1 = workbook.addWorksheet("Report Summary", {
      views: [{ showGridLines: true }],
    });
    s1.columns = [
      { width: 30 },
      { width: 35 },
    ];

    // Title Block
    s1.mergeCells("A1:B1");
    s1.getCell("A1").value = metadata.report_title || "Leave Summary Report";
    s1.getCell("A1").font = { name: "Calibri", size: 16, bold: true, color: { argb: "FF0F172A" } };
    s1.getCell("A1").alignment = { vertical: "middle" };
    s1.getRow(1).height = 30;

    // Metadata Rows
    const metaRows = [
      ["Selected Date Range", `${metadata.from_date} to ${metadata.to_date}`],
      ["Generated Date", new Date(metadata.generated_at).toLocaleString()],
      ["Generated By", metadata.generated_by || "Superior Admin"],
    ];
    metaRows.forEach((r) => {
      const row = s1.addRow(r);
      row.font = { name: "Calibri", size: 11 };
      row.getCell(1).font = { bold: true, color: { argb: "FF475569" } };
    });

    s1.addRow([]); // Blank line

    // Section Header: Executive Summary
    s1.mergeCells("A6:B6");
    s1.getCell("A6").value = "Executive Summary Metrics";
    s1.getCell("A6").fill = headerFill;
    s1.getCell("A6").font = headerFont;
    s1.getCell("A6").alignment = { vertical: "middle", horizontal: "left" };
    s1.getRow(6).height = 24;

    const summaryItems = [
      ["Total Leave Requests", summary.total_requests],
      ["Total Employees Who Took Leave", summary.total_employees_took_leave],
      ["Total Leave Days", summary.total_leave_days],
      ["Total Time Permission Hours", `${summary.total_time_permission_hours} hrs`],
      ["Approved Requests", summary.approved_requests],
      ["Pending Requests", summary.pending_requests],
      ["Rejected Requests", summary.rejected_requests],
      ["No Pay / Paycut Leave Count", summary.paycut_leave_count],
    ];

    summaryItems.forEach((item, idx) => {
      const row = s1.addRow(item);
      row.height = 20;
      row.getCell(1).font = { name: "Calibri", size: 11, bold: true, color: { argb: "FF334155" } };
      row.getCell(2).font = { name: "Calibri", size: 11, bold: true, color: { argb: "FF0F172A" } };
      row.getCell(1).border = thinBorder;
      row.getCell(2).border = thinBorder;
      if (idx % 2 === 0) {
        row.getCell(1).fill = accentFill;
        row.getCell(2).fill = accentFill;
      }
    });

    // =========================================================================
    // SHEET 2: Employee Leave Details
    // =========================================================================
    const s2 = workbook.addWorksheet("Employee Leave Details", {
      views: [{ showGridLines: true }],
    });
    s2.columns = [
      { header: "Employee Name", key: "employee_name", width: 22 },
      { header: "Department / Team", key: "department_name", width: 20 },
      { header: "Leave Type", key: "leave_type", width: 18 },
      { header: "Leave / Time Permission", key: "record_type", width: 22 },
      { header: "Leave Start Date", key: "start_date", width: 16 },
      { header: "No. of Leave Days", key: "leave_days", width: 18 },
      { header: "Time Permission Hours", key: "permission_hours", width: 22 },
      { header: "Substitute", key: "substitute_name", width: 20 },
      { header: "Assigned Work", key: "assigned_work", width: 26 },
      { header: "Status", key: "status", width: 16 },
      { header: "Approved By", key: "approved_by", width: 20 },
      { header: "Applied Date", key: "applied_date", width: 16 },
      { header: "Remarks", key: "remarks", width: 28 },
    ];

    // Style Header
    s2.getRow(1).height = 26;
    s2.getRow(1).eachCell((cell) => {
      cell.fill = headerFill;
      cell.font = headerFont;
      cell.alignment = { vertical: "middle", horizontal: "center" };
    });

    details.forEach((d, idx) => {
      const row = s2.addRow({
        employee_name: d.employee_name,
        department_name: d.department_name,
        leave_type: d.leave_type,
        record_type: d.record_type,
        start_date: d.start_date,
        leave_days: d.record_type === "Time Permission" ? "—" : d.leave_days,
        permission_hours: d.record_type === "Time Permission" ? `${d.permission_hours} hrs` : "—",
        substitute_name: d.substitute_name,
        assigned_work: d.assigned_work,
        status: d.status,
        approved_by: d.approved_by,
        applied_date: d.applied_date,
        remarks: d.remarks,
      });
      row.height = 20;
      row.eachCell((cell) => {
        cell.border = thinBorder;
        cell.font = { name: "Calibri", size: 10 };
        if (idx % 2 === 1) cell.fill = accentFill;
      });
    });

    // =========================================================================
    // SHEET 3: Employee-wise Total Summary
    // =========================================================================
    const s3 = workbook.addWorksheet("Employee-wise Total Summary", {
      views: [{ showGridLines: true }],
    });
    s3.columns = [
      { header: "Employee Name", key: "employee_name", width: 24 },
      { header: "Department / Team", key: "department_name", width: 22 },
      { header: "Total Leave Requests", key: "total_requests", width: 20 },
      { header: "Total Leave Days", key: "total_leave_days", width: 18 },
      { header: "Total Time Permission Hours", key: "total_permission_hours", width: 26 },
      { header: "Approved Count", key: "approved_count", width: 16 },
      { header: "Pending Count", key: "pending_count", width: 16 },
      { header: "Rejected Count", key: "rejected_count", width: 16 },
    ];

    s3.getRow(1).height = 26;
    s3.getRow(1).eachCell((cell) => {
      cell.fill = headerFill;
      cell.font = headerFont;
      cell.alignment = { vertical: "middle", horizontal: "center" };
    });

    employee_summary.forEach((emp, idx) => {
      const row = s3.addRow({
        employee_name: emp.employee_name,
        department_name: emp.department_name,
        total_requests: emp.total_requests,
        total_leave_days: emp.total_leave_days,
        total_permission_hours: `${emp.total_permission_hours} hrs`,
        approved_count: emp.approved_count,
        pending_count: emp.pending_count,
        rejected_count: emp.rejected_count,
      });
      row.height = 20;
      row.eachCell((cell) => {
        cell.border = thinBorder;
        cell.font = { name: "Calibri", size: 10 };
        if (idx % 2 === 1) cell.fill = accentFill;
      });
    });

    // =========================================================================
    // SHEET 4: Team-wise Summary
    // =========================================================================
    const s4 = workbook.addWorksheet("Team-wise Summary", {
      views: [{ showGridLines: true }],
    });
    s4.columns = [
      { header: "Department / Team", key: "team_name", width: 24 },
      { header: "Employees Took Leave", key: "employees_count", width: 22 },
      { header: "Total Leave Requests", key: "total_requests", width: 20 },
      { header: "Total Leave Days", key: "total_leave_days", width: 18 },
      { header: "Time Permission Hours", key: "total_permission_hours", width: 22 },
      { header: "Most Used Leave Type", key: "most_used_leave_type", width: 24 },
    ];

    s4.getRow(1).height = 26;
    s4.getRow(1).eachCell((cell) => {
      cell.fill = headerFill;
      cell.font = headerFont;
      cell.alignment = { vertical: "middle", horizontal: "center" };
    });

    team_summary.forEach((team, idx) => {
      const row = s4.addRow({
        team_name: team.team_name,
        employees_count: team.employees_count,
        total_requests: team.total_requests,
        total_leave_days: team.total_leave_days,
        total_permission_hours: `${team.total_permission_hours} hrs`,
        most_used_leave_type: team.most_used_leave_type,
      });
      row.height = 20;
      row.eachCell((cell) => {
        cell.border = thinBorder;
        cell.font = { name: "Calibri", size: 10 };
        if (idx % 2 === 1) cell.fill = accentFill;
      });
    });

    // =========================================================================
    // SHEET 5: Exceptions / Important Notes
    // =========================================================================
    const s5 = workbook.addWorksheet("Exceptions & Notes", {
      views: [{ showGridLines: true }],
    });
    s5.columns = [
      { width: 24 },
      { width: 22 },
      { width: 20 },
      { width: 16 },
      { width: 16 },
      { width: 26 },
    ];

    let rIdx = 1;

    const addSectionHeader = (title) => {
      s5.mergeCells(`A${rIdx}:F${rIdx}`);
      const c = s5.getCell(`A${rIdx}`);
      c.value = title;
      c.fill = subHeaderFill;
      c.font = { name: "Calibri", size: 11, bold: true, color: { argb: "FFFFFFFF" } };
      c.alignment = { vertical: "middle" };
      s5.getRow(rIdx).height = 22;
      rIdx++;
    };

    const addTableHeaders = (headers) => {
      const row = s5.getRow(rIdx);
      headers.forEach((h, i) => {
        const cell = row.getCell(i + 1);
        cell.value = h;
        cell.fill = headerFill;
        cell.font = headerFont;
        cell.border = thinBorder;
      });
      row.height = 22;
      rIdx++;
    };

    // 1. Paycut / No Pay Leaves
    addSectionHeader("1. Employees with No Pay / Paycut Leave");
    addTableHeaders(["Employee Name", "Department / Team", "Leave Type", "Start Date", "Paycut Units", "Status"]);
    if (exceptions.paycut_leaves.length === 0) {
      const row = s5.getRow(rIdx);
      row.getCell(1).value = "No paycut or no-pay leave records found in selected range.";
      row.getCell(1).font = { italic: true, color: { argb: "FF64748B" } };
      rIdx += 2;
    } else {
      exceptions.paycut_leaves.forEach((d) => {
        const row = s5.getRow(rIdx);
        row.getCell(1).value = d.employee_name;
        row.getCell(2).value = d.department_name;
        row.getCell(3).value = d.leave_type;
        row.getCell(4).value = d.start_date;
        row.getCell(5).value = d.paycut_units;
        row.getCell(6).value = d.status;
        row.eachCell((cell) => { cell.border = thinBorder; cell.font = { name: "Calibri", size: 10 }; });
        rIdx++;
      });
      rIdx++;
    }

    // 2. Pending Requests
    addSectionHeader("2. Pending Leave Requests (Action Required)");
    addTableHeaders(["Employee Name", "Department / Team", "Leave Type", "Start Date", "Units / Hours", "Current Status"]);
    if (exceptions.pending_leaves.length === 0) {
      const row = s5.getRow(rIdx);
      row.getCell(1).value = "No pending leave requests in selected range.";
      row.getCell(1).font = { italic: true, color: { argb: "FF64748B" } };
      rIdx += 2;
    } else {
      exceptions.pending_leaves.forEach((d) => {
        const row = s5.getRow(rIdx);
        row.getCell(1).value = d.employee_name;
        row.getCell(2).value = d.department_name;
        row.getCell(3).value = d.leave_type;
        row.getCell(4).value = d.start_date;
        row.getCell(5).value = d.record_type === "Time Permission" ? `${d.permission_hours} hrs` : `${d.leave_days} days`;
        row.getCell(6).value = d.status;
        row.eachCell((cell) => { cell.border = thinBorder; cell.font = { name: "Calibri", size: 10 }; });
        rIdx++;
      });
      rIdx++;
    }

    // 3. Rejected Requests
    addSectionHeader("3. Rejected Leave Requests");
    addTableHeaders(["Employee Name", "Department / Team", "Leave Type", "Start Date", "Units / Hours", "Remarks"]);
    if (exceptions.rejected_leaves.length === 0) {
      const row = s5.getRow(rIdx);
      row.getCell(1).value = "No rejected leave requests in selected range.";
      row.getCell(1).font = { italic: true, color: { argb: "FF64748B" } };
      rIdx += 2;
    } else {
      exceptions.rejected_leaves.forEach((d) => {
        const row = s5.getRow(rIdx);
        row.getCell(1).value = d.employee_name;
        row.getCell(2).value = d.department_name;
        row.getCell(3).value = d.leave_type;
        row.getCell(4).value = d.start_date;
        row.getCell(5).value = d.record_type === "Time Permission" ? `${d.permission_hours} hrs` : `${d.leave_days} days`;
        row.getCell(6).value = d.remarks;
        row.eachCell((cell) => { cell.border = thinBorder; cell.font = { name: "Calibri", size: 10 }; });
        rIdx++;
      });
      rIdx++;
    }

    // 4. High Usage Employees
    addSectionHeader("4. Employees with High Leave Usage (>= 3 Days or >= 4 Hours)");
    addTableHeaders(["Employee Name", "Department / Team", "Total Requests", "Leave Days", "Permission Hours", "Approved Count"]);
    if (exceptions.high_usage_employees.length === 0) {
      const row = s5.getRow(rIdx);
      row.getCell(1).value = "No employees exceeded the high usage threshold in selected range.";
      row.getCell(1).font = { italic: true, color: { argb: "FF64748B" } };
      rIdx += 2;
    } else {
      exceptions.high_usage_employees.forEach((emp) => {
        const row = s5.getRow(rIdx);
        row.getCell(1).value = emp.employee_name;
        row.getCell(2).value = emp.department_name;
        row.getCell(3).value = emp.total_requests;
        row.getCell(4).value = emp.total_leave_days;
        row.getCell(5).value = `${emp.total_permission_hours} hrs`;
        row.getCell(6).value = emp.approved_count;
        row.eachCell((cell) => { cell.border = thinBorder; cell.font = { name: "Calibri", size: 10 }; });
        rIdx++;
      });
    }

    return workbook;
  },
};
