import PDFDocument from "pdfkit";

export const pdfReportService = {
  async generateLeaveSummaryPdf(reportData) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: "A4",
          layout: "landscape",
          margin: 36,
          bufferPages: true,
        });

        const buffers = [];
        doc.on("data", (chunk) => buffers.push(chunk));
        doc.on("end", () => resolve(Buffer.concat(buffers)));
        doc.on("error", (err) => reject(err));

        const { metadata, summary, details, employee_summary, team_summary, leave_type_breakdown, exceptions } = reportData;

        // Colors
        const primaryColor = "#1E293B"; // Slate 800
        const secondaryColor = "#475569"; // Slate 600
        const accentColor = "#2563EB"; // Blue 600
        const tableHeaderBg = "#0F172A"; // Slate 900
        const tableRowAltBg = "#F8FAFC"; // Slate 50
        const borderColor = "#E2E8F0";

        // Helper: draw divider
        const drawDivider = (y) => {
          doc.save().strokeColor(borderColor).lineWidth(1).moveTo(36, y).lineTo(doc.page.width - 36, y).stroke().restore();
        };

        // Header Block
        doc.rect(36, 36, doc.page.width - 72, 60).fill("#F1F5F9");
        doc.fillColor(primaryColor).fontSize(18).font("Helvetica-Bold").text("LEAVE SUMMARY REPORT", 48, 48);
        doc.fillColor(secondaryColor).fontSize(10).font("Helvetica").text(
          `Date Range: ${metadata.from_date} to ${metadata.to_date}   |   Generated On: ${new Date(metadata.generated_at).toLocaleDateString()}   |   Generated By: ${metadata.generated_by || "Superior Admin"}`,
          48,
          74
        );

        // Section 1: Executive KPI Metrics Cards
        let currentY = 110;
        doc.fillColor(primaryColor).fontSize(13).font("Helvetica-Bold").text("1. Executive Summary Metrics", 36, currentY);
        currentY += 18;

        const kpis = [
          { label: "Total Requests", val: String(summary.total_requests), color: "#3B82F6" },
          { label: "Employees on Leave", val: String(summary.total_employees_took_leave), color: "#8B5CF6" },
          { label: "Total Leave Days", val: String(summary.total_leave_days), color: "#10B981" },
          { label: "Permission Hours", val: `${summary.total_time_permission_hours} hrs`, color: "#F59E0B" },
          { label: "Approved", val: String(summary.approved_requests), color: "#059669" },
          { label: "Pending", val: String(summary.pending_requests), color: "#D97706" },
          { label: "Rejected", val: String(summary.rejected_requests), color: "#DC2626" },
          { label: "No Pay / Paycut", val: String(summary.paycut_leave_count), color: "#7C3AED" },
        ];

        const cardWidth = (doc.page.width - 72 - (kpis.length - 1) * 6) / kpis.length;
        const cardHeight = 44;

        kpis.forEach((kpi, i) => {
          const cardX = 36 + i * (cardWidth + 6);
          doc.save().roundedRect(cardX, currentY, cardWidth, cardHeight, 4).fill("#FFFFFF").strokeColor(borderColor).lineWidth(1).stroke().restore();
          doc.save().fillColor(kpi.color).fontSize(13).font("Helvetica-Bold").text(kpi.val, cardX, currentY + 8, { width: cardWidth, align: "center" }).restore();
          doc.save().fillColor(secondaryColor).fontSize(7.5).font("Helvetica").text(kpi.label, cardX, currentY + 26, { width: cardWidth, align: "center" }).restore();
        });

        currentY += cardHeight + 20;

        // Helper: Check Page Break
        const checkPageBreak = (neededHeight) => {
          if (currentY + neededHeight > doc.page.height - 45) {
            doc.addPage();
            currentY = 40;
            return true;
          }
          return false;
        };

        // Helper: Table Renderer
        const renderTable = ({ title, columns, rows, emptyText }) => {
          checkPageBreak(50);
          if (title) {
            doc.fillColor(primaryColor).fontSize(12).font("Helvetica-Bold").text(title, 36, currentY);
            currentY += 16;
          }

          const tableWidth = doc.page.width - 72;
          const rowHeight = 18;
          const headerHeight = 20;

          // Render Table Header
          doc.rect(36, currentY, tableWidth, headerHeight).fill(tableHeaderBg);
          let colX = 36;
          columns.forEach((col) => {
            doc.fillColor("#FFFFFF").fontSize(8).font("Helvetica-Bold").text(col.header, colX + 4, currentY + 5, {
              width: col.width - 8,
              align: col.align || "left",
            });
            colX += col.width;
          });
          currentY += headerHeight;

          if (rows.length === 0) {
            doc.rect(36, currentY, tableWidth, 24).fill("#FFFFFF").strokeColor(borderColor).lineWidth(0.5).stroke();
            doc.fillColor("#64748B").fontSize(8.5).font("Helvetica-Oblique").text(emptyText || "No records available for selected date range.", 44, currentY + 7);
            currentY += 28;
            return;
          }

          rows.forEach((row, rIdx) => {
            checkPageBreak(rowHeight + 10);
            const fillBg = rIdx % 2 === 1 ? tableRowAltBg : "#FFFFFF";
            doc.rect(36, currentY, tableWidth, rowHeight).fill(fillBg).strokeColor(borderColor).lineWidth(0.5).stroke();

            let cX = 36;
            columns.forEach((col) => {
              const val = String(row[col.key] !== undefined && row[col.key] !== null ? row[col.key] : "—");
              doc.fillColor("#1E293B").fontSize(7.5).font("Helvetica").text(val, cX + 4, currentY + 4.5, {
                width: col.width - 8,
                align: col.align || "left",
                lineBreak: false,
                ellipsis: true,
              });
              cX += col.width;
            });
            currentY += rowHeight;
          });

          currentY += 16;
        };

        // Section 2: Employee Leave Details Table
        const totalW = doc.page.width - 72; // ~770 pt
        renderTable({
          title: "2. Employee Leave Details",
          columns: [
            { header: "Employee Name", key: "employee_name", width: totalW * 0.16 },
            { header: "Department", key: "department_name", width: totalW * 0.13 },
            { header: "Leave Type", key: "leave_type", width: totalW * 0.13 },
            { header: "Type", key: "record_type", width: totalW * 0.11 },
            { header: "Start Date", key: "start_date", width: totalW * 0.09 },
            { header: "Days", key: "leave_days_str", width: totalW * 0.06, align: "center" },
            { header: "Hours", key: "permission_hours_str", width: totalW * 0.07, align: "center" },
            { header: "Status", key: "status", width: totalW * 0.11 },
            { header: "Approved By", key: "approved_by", width: totalW * 0.14 },
          ],
          rows: details.map((d) => ({
            ...d,
            leave_days_str: d.record_type === "Time Permission" ? "—" : d.leave_days,
            permission_hours_str: d.record_type === "Time Permission" ? `${d.permission_hours}h` : "—",
          })),
          emptyText: "No employee leave records found in the selected date range.",
        });

        // Section 3: Employee-wise Total Summary Table
        renderTable({
          title: "3. Employee-wise Total Summary",
          columns: [
            { header: "Employee Name", key: "employee_name", width: totalW * 0.22 },
            { header: "Department / Team", key: "department_name", width: totalW * 0.20 },
            { header: "Total Requests", key: "total_requests", width: totalW * 0.12, align: "center" },
            { header: "Leave Days", key: "total_leave_days", width: totalW * 0.11, align: "center" },
            { header: "Permission Hours", key: "hours_str", width: totalW * 0.13, align: "center" },
            { header: "Approved", key: "approved_count", width: totalW * 0.07, align: "center" },
            { header: "Pending", key: "pending_count", width: totalW * 0.07, align: "center" },
            { header: "Rejected", key: "rejected_count", width: totalW * 0.08, align: "center" },
          ],
          rows: employee_summary.map((e) => ({
            ...e,
            hours_str: `${e.total_permission_hours} hrs`,
          })),
          emptyText: "No employee summary available for this range.",
        });

        // Section 4: Team-wise Summary Table
        renderTable({
          title: "4. Team-wise Summary",
          columns: [
            { header: "Department / Team", key: "team_name", width: totalW * 0.25 },
            { header: "Employees Took Leave", key: "employees_count", width: totalW * 0.16, align: "center" },
            { header: "Total Requests", key: "total_requests", width: totalW * 0.14, align: "center" },
            { header: "Total Leave Days", key: "total_leave_days", width: totalW * 0.14, align: "center" },
            { header: "Permission Hours", key: "hours_str", width: totalW * 0.14, align: "center" },
            { header: "Most Used Leave Type", key: "most_used_leave_type", width: totalW * 0.17 },
          ],
          rows: team_summary.map((t) => ({
            ...t,
            hours_str: `${t.total_permission_hours} hrs`,
          })),
          emptyText: "No team summary data available.",
        });

        // Section 5: Leave Type Breakdown Table
        renderTable({
          title: "5. Leave Type Breakdown",
          columns: [
            { header: "Leave Type", key: "leave_type", width: totalW * 0.35 },
            { header: "Request Count", key: "count", width: totalW * 0.20, align: "center" },
            { header: "Total Leave Days", key: "days_str", width: totalW * 0.22, align: "center" },
            { header: "Total Permission Hours", key: "hours_str", width: totalW * 0.23, align: "center" },
          ],
          rows: (leave_type_breakdown || []).map((lt) => ({
            ...lt,
            days_str: lt.leave_type === "Time Permission" ? "—" : lt.total_days,
            hours_str: lt.leave_type === "Time Permission" ? `${lt.total_hours} hrs` : "—",
          })),
          emptyText: "No leave type breakdown data available.",
        });

        // Section 6: Exceptions / Important Notes
        checkPageBreak(60);
        doc.fillColor(primaryColor).fontSize(12).font("Helvetica-Bold").text("6. Exceptions & Important Notes", 36, currentY);
        currentY += 16;

        // Sub 6.1: Paycut leaves
        renderTable({
          title: "6.1 Employees with No Pay / Paycut Leave",
          columns: [
            { header: "Employee Name", key: "employee_name", width: totalW * 0.25 },
            { header: "Department", key: "department_name", width: totalW * 0.22 },
            { header: "Leave Type", key: "leave_type", width: totalW * 0.18 },
            { header: "Start Date", key: "start_date", width: totalW * 0.12 },
            { header: "Paycut Units", key: "paycut_units", width: totalW * 0.11, align: "center" },
            { header: "Status", key: "status", width: totalW * 0.12 },
          ],
          rows: exceptions.paycut_leaves,
          emptyText: "No employees took paycut or no-pay leave during this period.",
        });

        // Sub 6.2: Pending Leaves
        renderTable({
          title: "6.2 Pending Leave Requests (Action Required)",
          columns: [
            { header: "Employee Name", key: "employee_name", width: totalW * 0.25 },
            { header: "Department", key: "department_name", width: totalW * 0.22 },
            { header: "Leave Type", key: "leave_type", width: totalW * 0.18 },
            { header: "Start Date", key: "start_date", width: totalW * 0.12 },
            { header: "Units / Hours", key: "duration_str", width: totalW * 0.11, align: "center" },
            { header: "Status", key: "status", width: totalW * 0.12 },
          ],
          rows: exceptions.pending_leaves.map((p) => ({
            ...p,
            duration_str: p.record_type === "Time Permission" ? `${p.permission_hours} hrs` : `${p.leave_days} days`,
          })),
          emptyText: "No pending leave requests in this date range.",
        });

        // Sub 6.3: Rejected Leaves
        renderTable({
          title: "6.3 Rejected Leave Requests",
          columns: [
            { header: "Employee Name", key: "employee_name", width: totalW * 0.25 },
            { header: "Department", key: "department_name", width: totalW * 0.20 },
            { header: "Leave Type", key: "leave_type", width: totalW * 0.16 },
            { header: "Start Date", key: "start_date", width: totalW * 0.11 },
            { header: "Remarks / Reason", key: "remarks", width: totalW * 0.28 },
          ],
          rows: exceptions.rejected_leaves,
          emptyText: "No rejected leave requests in this date range.",
        });

        // Add Footers with Page Numbers on all buffered pages
        const pages = doc.bufferedPageRange();
        for (let i = 0; i < pages.count; i++) {
          doc.switchToPage(i);
          drawDivider(doc.page.height - 30);
          doc.fillColor("#94A3B8").fontSize(7.5).font("Helvetica").text(
            "LeaveEase Enterprise Management System  •  Confidential Superior Admin Report",
            36,
            doc.page.height - 22,
            { width: doc.page.width / 2, align: "left" }
          );
          doc.fillColor("#94A3B8").fontSize(7.5).font("Helvetica").text(
            `Page ${i + 1} of ${pages.count}`,
            doc.page.width / 2,
            doc.page.height - 22,
            { width: doc.page.width / 2 - 36, align: "right" }
          );
        }

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  },
};
